<a href="https://colab.research.google.com/github/chinedudev9/Machine_Learning_Project/blob/main/Movie_Recommendation_system.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Import Dependencies

In [1]:
import pandas as pd
import numpy as np
import difflib
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [2]:
movies_data = pd.read_csv('/content/movies.csv', engine='python')

In [3]:
movies_data.head()

,index,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,cast,crew,director
0,0,237000000,Action Adventure Fantasy Science Fiction,http://www.avatarmovie.com/,19995,culture clash future space war space colony so...,en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,Sam Worthington Zoe Saldana Sigourney Weaver S...,"[{'name': 'Stephen E. Rivkin', 'gender': 0, 'd...",James Cameron
1,1,300000000,Adventure Fantasy Action,http://disney.go.com/disneypictures/pirates/,285,ocean drug abuse exotic island east india trad...,en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,...,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,Johnny Depp Orlando Bloom Keira Knightley Stel...,"[{'name': 'Dariusz Wolski', 'gender': 2, 'depa...",Gore Verbinski
2,2,245000000,Action Adventure Crime,http://www.sonypictures.com/movies/spectre/,206647,spy based on novel secret agent sequel mi6,en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,...,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466,Daniel Craig Christoph Waltz L\u00e9a Seydoux ...,"[{'name': 'Thomas Newman', 'gender': 2, 'depar...",Sam Mendes
3,3,250000000,Action Crime Drama Thriller,http://www.thedarkknightrises.com/,49026,dc comics crime fighter terrorist secret ident...,en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,...,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106,Christian Bale Michael Caine Gary Oldman Anne ...,"[{'name': 'Hans Zimmer', 'gender': 2, 'departm...",Christopher Nolan
4,4,260000000,Action Adventure Science Fiction,http://movies.disney.com/john-carter,49529,based on novel mars medallion space travel pri...,en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,...,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124,Taylor Kitsch Lynn Collins Samantha Morton Wil...,"[{'name': 'Andrew Stanton', 'gender': 2, 'depa...",Andrew Stanton

In [4]:
#checking for null data
movies_data.isnull().sum()

index                      0
budget                     0
genres                    28
homepage                3091
id                         0
keywords                 412
original_language          0
original_title             0
overview                   3
popularity                 0
production_companies       0
production_countries       0
release_date               1
revenue                    0
runtime                    2
spoken_languages           0
status                     0
tagline                  844
title                      0
vote_average               0
vote_count                 0
cast                      43
crew                       0
director                  30
dtype: int64

In [5]:
#selecting the relevant column
selected_data = ['genres', 'keywords', 'tagline', 'cast', 'director']
print(selected_data)

['genres', 'keywords', 'tagline', 'cast', 'director']

In [6]:
#replacing the missing data in the selected_data with empty string by looping
for i in selected_data:
  movies_data[i] = movies_data[i].fillna('')

In [7]:
#concatenate the data in the selected_data
combined_data = movies_data['genres']+' '+movies_data['keywords']+' '+movies_data['tagline']+' '+movies_data['cast']+' '+movies_data['director']

In [8]:
print(combined_data)

0       Action Adventure Fantasy Science Fiction cultu...
1       Adventure Fantasy Action ocean drug abuse exot...
2       Action Adventure Crime spy based on novel secr...
3       Action Crime Drama Thriller dc comics crime fi...
4       Action Adventure Science Fiction based on nove...
                              ...
4798    Action Crime Thriller united states\u2013mexic...
4799    Comedy Romance  A newlywed couple's honeymoon ...
4800    Comedy Drama Romance TV Movie date love at fir...
4801      A New Yorker in Shanghai Daniel Henney Eliza...
4802    Documentary obsession camcorder crush dream gi...
Length: 4803, dtype: object

In [9]:
combined_data.isnull().sum()

np.int64(0)

In [10]:
#convert the text data to numeriacal data
vectorizer = TfidfVectorizer()

In [11]:
numerical_data = vectorizer.fit_transform(combined_data)

In [12]:
print(numerical_data)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 124266 stored elements and shape (4803, 17318)>
  Coords	Values
  (0, 201)	0.07860022416510505
  (0, 274)	0.09021200873707368
  (0, 5274)	0.11108562744414445
  (0, 13599)	0.1036413987316636
  (0, 5437)	0.1036413987316636
  (0, 3678)	0.21392179219912877
  (0, 3065)	0.22208377802661425
  (0, 5836)	0.1646750903586285
  (0, 14378)	0.33962752210959823
  (0, 16587)	0.12549432354918996
  (0, 3225)	0.24960162956997736
  (0, 14271)	0.21392179219912877
  (0, 4945)	0.24025852494110758
  (0, 15261)	0.07095833561276566
  (0, 16998)	0.1282126322850579
  (0, 11192)	0.09049319826481456
  (0, 11503)	0.27211310056983656
  (0, 13349)	0.15021264094167086
  (0, 17007)	0.23643326319898797
  (0, 17290)	0.20197912553916567
  (0, 13319)	0.2177470539412484
  (0, 14064)	0.20596090415084142
  (0, 16668)	0.19843263965100372
  (0, 14608)	0.15150672398763912
  (0, 8756)	0.22709015857011816
  :	:
  (4801, 403)	0.17727585190343229
  (4801, 4835)	0.24713765026964
  (4801, 17266)	0.28860981849329476
  (4801, 13835)	0.27870029291200094
  (4801, 13175)	0.28860981849329476
  (4801, 17150)	0.3025765103586468
  (4801, 3511)	0.3025765103586468
  (4801, 13948)	0.3025765103586468
  (4801, 7269)	0.3025765103586468
  (4802, 11161)	0.17867407682173203
  (4802, 4518)	0.16784466610624255
  (4802, 2129)	0.3099656128577656
  (4802, 4980)	0.16078053641367315
  (4802, 6155)	0.18056463596934083
  (4802, 3436)	0.21753405888348784
  (4802, 4528)	0.19504460807622875
  (4802, 1316)	0.1960747079005741
  (4802, 12989)	0.1696476532191718
  (4802, 4371)	0.1538239182675544
  (4802, 6417)	0.21753405888348784
  (4802, 4608)	0.24002350969074696
  (4802, 2425)	0.24002350969074696
  (4802, 3654)	0.262512960498006
  (4802, 5367)	0.22969114490410403
  (4802, 6996)	0.5700048226105303

Finding the similarity

In [13]:
cosine_similarity = cosine_similarity(numerical_data)

In [14]:
print(cosine_similarity)

[[1.         0.07219487 0.037733   ... 0.         0.         0.        ]
 [0.07219487 1.         0.03281499 ... 0.03575545 0.         0.        ]
 [0.037733   0.03281499 1.         ... 0.         0.05389661 0.        ]
 ...
 [0.         0.03575545 0.         ... 1.         0.         0.02651502]
 [0.         0.         0.05389661 ... 0.         1.         0.        ]
 [0.         0.         0.         ... 0.02651502 0.         1.        ]]

In [15]:
cosine_similarity.shape

(4803, 4803)

In [16]:
#get movie from user
movie_name = input('Enter the movie name: ')

Enter the movie name: legend of the seeker

In [17]:
#get the list of all the title
title = movies_data['title'].tolist()
print(title)

['Avatar', "Pirates of the Caribbean: At World's End", 'Spectre', 'The Dark Knight Rises', 'John Carter', 'Spider-Man 3', 'Tangled', 'Avengers: Age of Ultron', 'Harry Potter and the Half-Blood Prince', 'Batman v Superman: Dawn of Justice', 'Superman Returns', 'Quantum of Solace', "Pirates of the Caribbean: Dead Man's Chest", 'The Lone Ranger', 'Man of Steel', 'The Chronicles of Narnia: Prince Caspian', 'The Avengers', 'Pirates of the Caribbean: On Stranger Tides', 'Men in Black 3', 'The Hobbit: The Battle of the Five Armies', 'The Amazing Spider-Man', 'Robin Hood', 'The Hobbit: The Desolation of Smaug', 'The Golden Compass', 'King Kong', 'Titanic', 'Captain America: Civil War', 'Battleship', 'Jurassic World', 'Skyfall', 'Spider-Man 2', 'Iron Man 3', 'Alice in Wonderland', 'X-Men: The Last Stand', 'Monsters University', 'Transformers: Revenge of the Fallen', 'Transformers: Age of Extinction', 'Oz: The Great and Powerful', 'The Amazing Spider-Man 2', 'TRON: Legacy', 'Cars 2', 'Green Lantern', 'Toy Story 3', 'Terminator Salvation', 'Furious 7', 'World War Z', 'X-Men: Days of Future Past', 'Star Trek Into Darkness', 'Jack the Giant Slayer', 'The Great Gatsby', 'Prince of Persia: The Sands of Time', 'Pacific Rim', 'Transformers: Dark of the Moon', 'Indiana Jones and the Kingdom of the Crystal Skull', 'The Good Dinosaur', 'Brave', 'Star Trek Beyond', 'WALL·E', 'Rush Hour 3', '2012', 'A Christmas Carol', 'Jupiter Ascending', 'The Legend of Tarzan', 'The Chronicles of Narnia: The Lion, the Witch and the Wardrobe', 'X-Men: Apocalypse', 'The Dark Knight', 'Up', 'Monsters vs Aliens', 'Iron Man', 'Hugo', 'Wild Wild West', 'The Mummy: Tomb of the Dragon Emperor', 'Suicide Squad', 'Evan Almighty', 'Edge of Tomorrow', 'Waterworld', 'G.I. Joe: The Rise of Cobra', 'Inside Out', 'The Jungle Book', 'Iron Man 2', 'Snow White and the Huntsman', 'Maleficent', 'Dawn of the Planet of the Apes', 'The Lovers', '47 Ronin', 'Captain America: The Winter Soldier', 'Shrek Forever After', 'Tomorrowland', 'Big Hero 6', 'Wreck-It Ralph', 'The Polar Express', 'Independence Day: Resurgence', 'How to Train Your Dragon', 'Terminator 3: Rise of the Machines', 'Guardians of the Galaxy', 'Interstellar', 'Inception', 'Shin Godzilla', 'The Hobbit: An Unexpected Journey', 'The Fast and the Furious', 'The Curious Case of Benjamin Button', 'X-Men: First Class', 'The Hunger Games: Mockingjay - Part 2', "The Sorcerer's Apprentice", 'Poseidon', 'Alice Through the Looking Glass', 'Shrek the Third', 'Warcraft', 'Terminator Genisys', 'The Chronicles of Narnia: The Voyage of the Dawn Treader', 'Pearl Harbor', 'Transformers', 'Alexander', 'Harry Potter and the Order of the Phoenix', 'Harry Potter and the Goblet of Fire', 'Hancock', 'I Am Legend', 'Charlie and the Chocolate Factory', 'Ratatouille', 'Batman Begins', 'Madagascar: Escape 2 Africa', 'Night at the Museum: Battle of the Smithsonian', 'X-Men Origins: Wolverine', 'The Matrix Revolutions', 'Frozen', 'The Matrix Reloaded', 'Thor: The Dark World', 'Mad Max: Fury Road', 'Angels & Demons', 'Thor', 'Bolt', 'G-Force', 'Wrath of the Titans', 'Dark Shadows', 'Mission: Impossible - Rogue Nation', 'The Wolfman', 'Bee Movie', 'Kung Fu Panda 2', 'The Last Airbender', 'Mission: Impossible III', 'White House Down', 'Mars Needs Moms', 'Flushed Away', 'Pan', 'Mr. Peabody & Sherman', 'Troy', "Madagascar 3: Europe's Most Wanted", 'Die Another Day', 'Ghostbusters', 'Armageddon', 'Men in Black II', 'Beowulf', 'Kung Fu Panda 3', 'Mission: Impossible - Ghost Protocol', 'Rise of the Guardians', 'Fun with Dick and Jane', 'The Last Samurai', 'Exodus: Gods and Kings', 'Star Trek', 'Spider-Man', 'How to Train Your Dragon 2', 'Gods of Egypt', 'Stealth', 'Watchmen', 'Lethal Weapon 4', 'Hulk', 'G.I. Joe: Retaliation', 'Sahara', 'Final Fantasy: The Spirits Within', 'Captain America: The First Avenger', 'The World Is Not Enough', 'Master and Commander: The Far Side of the World', 'The Twilight Saga: Breaking Dawn - Part 2', 'Happy Feet Two', 'The Incredible Hulk', 'The BFG', 'The Revenant', 'Turbo', 'Rango', 'Penguins of Madagascar', 'The Bourne Ultimatum', 'Kung Fu Panda', 'Ant-Man', 'The Hunger Games: Catching Fire', 'Home', 'War of the Worlds', 'Bad Boys II', 'Puss in Boots', 'Salt', 'Noah', 'The Adventures of Tintin', 'Harry Potter and the Prisoner of Azkaban', 'Australia', 'After Earth', 'Dinosaur', 'Night at the Museum: Secret of the Tomb', 'Megamind', "Harry Potter and the Philosopher's Stone", 'R.I.P.D.', 'Pirates of the Caribbean: The Curse of the Black Pearl', 'The Hunger Games: Mockingjay - Part 1', 'The Da Vinci Code', 'Rio 2', 'X2', 'Fast Five', 'Sherlock Holmes: A Game of Shadows', 'Clash of the Titans', 'Total Recall', 'The 13th Warrior', 'The Bourne Legacy', 'Batman & Robin', 'How the Grinch Stole Christmas', 'The Day After Tomorrow', 'Mission: Impossible II', 'The Perfect Storm', 'Fantastic 4: Rise of the Silver Surfer', 'Life of Pi', 'Ghost Rider', 'Jason Bourne', "Charlie's Angels: Full Throttle", 'Prometheus', 'Stuart Little 2', 'Elysium', 'The Chronicles of Riddick', 'RoboCop', 'Speed Racer', 'How Do You Know', 'Knight and Day', 'Oblivion', 'Star Wars: Episode III - Revenge of the Sith', 'Star Wars: Episode II - Attack of the Clones', 'Monsters, Inc.', 'The Wolverine', 'Star Wars: Episode I - The Phantom Menace', 'The Croods', 'Asterix at the Olympic Games', 'Windtalkers', "The Huntsman: Winter's War", 'Teenage Mutant Ninja Turtles', 'Gravity', "Dante's Peak", 'Teenage Mutant Ninja Turtles: Out of the Shadows', 'Fantastic Four', 'Night at the Museum', 'San Andreas', 'Tomorrow Never Dies', 'The Patriot', "Ocean's Twelve", 'Mr. & Mrs. Smith', 'Insurgent', 'The Aviator', "Gulliver's Travels", 'The Green Hornet', '300: Rise of an Empire', 'The Smurfs', 'Home on the Range', 'Allegiant', 'Real Steel', 'The Smurfs 2', 'Speed 2: Cruise Control', "Ender's Game", 'Live Free or Die Hard', 'The Lord of the Rings: The Fellowship of the Ring', 'Around the World in 80 Days', 'Ali', 'The Cat in the Hat', 'I, Robot', 'Kingdom of Heaven', 'Stuart Little', 'The Princess and the Frog', 'The Martian', 'The Island', 'Town & Country', 'Gone in Sixty Seconds', 'Gladiator', 'Minority Report', 'Harry Potter and the Chamber of Secrets', 'Casino Royale', 'Planet of the Apes', 'Terminator 2: Judgment Day', 'Public Enemies', 'American Gangster', 'True Lies', 'The Taking of Pelham 1 2 3', 'Little Fockers', 'The Other Guys', 'Eraser', 'Django Unchained', 'The Hunchback of Notre Dame', "The Emperor's New Groove", 'The Expendables 2', 'National Treasure', 'Eragon', 'Where the Wild Things Are', 'Epic', 'The Tourist', 'End of Days', 'Blood Diamond', 'The Wolf of Wall Street', 'Batman Forever', 'Starship Troopers', 'Cloud Atlas', "Legend of the Guardians: The Owls of Ga'Hoole", 'Catwoman', 'Hercules', 'Treasure Planet', 'Land of the Lost', 'The Expendables 3', 'Point Break', 'Son of the Mask', 'In the Heart of the Sea', 'The Adventures of Pluto Nash', 'Green Zone', 'The Peanuts Movie', 'The Spanish Prisoner', 'The Mummy Returns', 'Gangs of New York', 'The Flowers of War', "Surf's Up", 'The Stepford Wives', 'Black Hawk Down', 'The Campaign', 'The Fifth Element', 'Sex and the City 2', 'The Road to El Dorado', 'Ice Age: Continental Drift', 'Cinderella', 'The Lovely Bones', 'Finding Nemo', 'The Lord of the Rings: The Return of the King', 'The Lord of the Rings: The Two Towers', 'Seventh Son', 'Lara Croft: Tomb Raider', 'Transcendence', 'Jurassic Park III', 'Rise of the Planet of the Apes', 'The Spiderwick Chronicles', 'A Good Day to Die Hard', 'The Alamo', 'The Incredibles', 'Cutthroat Island', 'Percy Jackson & the Olympians: The Lightning Thief', 'Men in Black', 'Toy Story 2', 'Unstoppable', 'Rush Hour 2', 'What Lies Beneath', 'Cloudy with a Chance of Meatballs', 'Ice Age: Dawn of the Dinosaurs', 'The Secret Life of Walter Mitty', "Charlie's Angels", 'The Departed', 'Mulan', 'Tropic Thunder', 'The Girl with the Dragon Tattoo', 'Die Hard: With a Vengeance', 'Sherlock Holmes', 'Ben-Hur', 'Atlantis: The Lost Empire', 'Alvin and the Chipmunks: The Road Chip', 'Valkyrie', "You Don't Mess with the Zohan", 'Pixels', 'A.I. Artificial Intelligence', 'The Haunted Mansion', 'Contact', 'Hollow Man', 'The Interpreter', 'Percy Jackson: Sea of Monsters', 'Lara Croft Tomb Raider: The Cradle of Life', 'Now You See Me 2', 'The Saint', 'Spy Game', 'Mission to Mars', 'Rio', 'Bicentennial Man', 'Volcano', "The Devil's Own", 'K-19: The Widowmaker', 'Conan the Barbarian', 'Cinderella Man', 'The Nutcracker: The Untold Story', 'Seabiscuit', 'Twister', 'Cast Away', 'Happy Feet', 'The Bourne Supremacy', 'Air Force One', "Ocean's Eleven", 'The Three Musketeers', 'Hotel Transylvania', 'Enchanted', 'Safe House', '102 Dalmatians', 'Tower Heist', 'The Holiday', 'Enemy of the State', "It's Complicated", "Ocean's Thirteen", 'Open Season', 'Divergent', 'Enemy at the Gates', 'The Rundown', 'Last Action Hero', 'Memoirs of a Geisha', 'The Fast and the Furious: Tokyo Drift', 'Arthur Christmas', 'Meet Joe Black', 'Collateral Damage', 'All That Jazz', 'Mirror Mirror', 'Scott Pilgrim vs. the World', 'The Core', 'Nutty Professor II: The Klumps', 'Scooby-Doo', 'Dredd', 'Click', 'Creepshow', 'Cats & Dogs 2 : The Revenge of Kitty Galore', 'Jumper', 'Hellboy II: The Golden Army', 'Zodiac', 'The 6th Day', 'Bruce Almighty', 'The Expendables', 'Mission: Impossible', 'The Hunger Games', 'The Hangover Part II', 'Batman Returns', 'Over the Hedge', 'Lilo & Stitch', "Charlotte's Web", 'Deep Impact', 'RED 2', 'The Longest Yard', 'Alvin and the Chipmunks: Chipwrecked', 'Grown Ups 2', 'Get Smart', "Something's Gotta Give", 'Shutter Island', 'Four Christmases', 'Robots', 'Face/Off', 'Bedtime Stories', 'Road to Perdition', 'Just Go with It', 'Con Air', 'Eagle Eye', 'Cold Mountain', 'The Book of Eli', 'Flubber', 'The Haunting', 'Space Jam', 'The Pink Panther', 'The Day the Earth Stood Still', 'Conspiracy Theory', 'Fury', 'Six Days Seven Nights', 'Yogi Bear', 'Spirit: Stallion of the Cimarron', 'Zookeeper', 'Lost in Space', 'The Manchurian Candidate', 'Déjà Vu', 'Hotel Transylvania 2', 'Fantasia 2000', 'The Time Machine', 'Mighty Joe Young', 'Swordfish', 'The Legend of Zorro', 'What Dreams May Come', 'Little Nicky', 'The Brothers Grimm', 'Mars Attacks!', 'Evolution', 'The Edge', 'Surrogates', 'Thirteen Days', 'Daylight', 'Walking With Dinosaurs', 'Battlefield Earth', 'Looney Tunes: Back in Action', 'Nine', 'Timeline', 'The Postman', 'Babe: Pig in the City', 'The Last Witch Hunter', 'Red Planet', 'Arthur and the Invisibles', 'Oceans', 'A Sound of Thunder', 'Pompeii', 'Top Cat Begins', 'A Beautiful Mind', 'The Lion King', 'Journey 2: The Mysterious Island', 'Cloudy with a Chance of Meatballs 2', 'Red Dragon', 'Hidalgo', 'Jack and Jill', '2 Fast 2 Furious', 'The Little Prince', 'The Invasion', 'The Adventures of Rocky & Bullwinkle', 'The Secret Life of Pets', 'The League of Extraordinary Gentlemen', 'Despicable Me 2', 'Independence Day', 'The Lost World: Jurassic Park', 'Madagascar', 'Children of Men', 'X-Men', 'Wanted', 'The Rock', 'Ice Age: The Meltdown', '50 First Dates', 'Hairspray', 'Exorcist: The Beginning', 'Inspector Gadget', 'Now You See Me', 'Grown Ups', 'The Terminal', 'Hotel for Dogs', 'Vertical Limit', "Charlie Wilson's War", 'Shark Tale', 'Dreamgirls', 'Be Cool', 'Munich', 'Tears of the Sun', 'Killers', 'The Man from U.N.C.L.E.', 'Spanglish', 'Monster House', 'Bandits', 'First Knight', 'Anna and the King', 'Immortals', 'Hostage', 'Titan A.E.', 'Hollywood Homicide', 'Soldier', 'Carriers', 'Monkeybone', 'Flight of the Phoenix', 'Unbreakable', 'Minions', 'Sucker Punch', 'Snake Eyes', 'Sphere', 'The Angry Birds Movie', "Fool's Gold", 'Funny People', 'The Kingdom', 'Talladega Nights: The Ballad of Ricky Bobby', 'Dr. Dolittle 2', 'Braveheart', 'Jarhead', 'The Simpsons Movie', 'The Majestic', 'Driven', 'Two Brothers', 'The Village', 'Doctor Dolittle', 'Signs', 'Shrek 2', 'Cars', 'Runaway Bride', 'xXx', 'The SpongeBob Movie: Sponge Out of Water', 'Ransom', 'Inglourious Basterds', 'Hook', 'Die Hard 2', 'S.W.A.T.', 'Vanilla Sky', 'Lady in the Water', 'AVP: Alien vs. Predator', 'Alvin and the Chipmunks: The Squeakquel', 'We Were Soldiers', 'Olympus Has Fallen', 'Star Trek: Insurrection', 'Battle: Los Angeles', 'Big Fish', 'Wolf', 'War Horse', 'The Monuments Men', 'The Abyss', 'Wall Street: Money Never Sleeps', 'Dracula Untold', 'The Siege', 'Stardust', 'Seven Years in Tibet', 'The Dilemma', 'Bad Company', 'Doom', 'I Spy', 'Underworld: Awakening', 'Rock of Ages', "Hart's War", 'Killer Elite', 'Rollerball', 'Ballistic: Ecks vs. Sever', 'Hard Rain', 'Osmosis Jones', "Legends of Oz: Dorothy's Return", 'Blackhat', 'Sky Captain and the World of Tomorrow', 'Basic Instinct 2', 'Escape Plan', 'The Legend of Hercules', 'The Sum of All Fears', 'The Twilight Saga: Eclipse', 'The Score', 'Despicable Me', 'Money Train', 'Ted 2', 'Agora', 'Mystery Men', 'Hall Pass', 'The Insider', 'The Finest Hours', 'Body of Lies', 'Dinner for Schmucks', 'Abraham Lincoln: Vampire Hunter', 'Entrapment', 'The X Files', 'The Last Legion', 'Saving Private Ryan', 'Need for Speed', 'What Women Want', 'Ice Age', 'Dreamcatcher', 'Lincoln', 'The Matrix', 'Apollo 13', 'The Santa Clause 2', 'Les Misérables', "You've Got Mail", 'Step Brothers', 'The Mask of Zorro', 'Due Date', 'Unbroken', 'Space Cowboys', 'Cliffhanger', 'Broken Arrow', 'The Kid', 'World Trade Center', 'Mona Lisa Smile', 'The Dictator', 'Eyes Wide Shut', 'Annie', 'Focus', 'This Means War', 'Blade: Trinity', 'Red Dawn', 'Primary Colors', 'Resident Evil: Retribution', 'Death Race', 'The Long Kiss Goodnight', 'Proof of Life', 'Zathura: A Space Adventure', 'Fight Club', 'We Are Marshall', 'Hudson Hawk', 'Lucky Numbers', 'I, Frankenstein', 'Oliver Twist', 'Elektra', 'Sin City: A Dame to Kill For', 'Random Hearts', 'Everest', 'Perfume: The Story of a Murderer', 'Austin Powers in Goldmember', 'Astro Boy', 'Jurassic Park', 'Wyatt Earp', 'Clear and Present Danger', 'Dragon Blade', 'Little Man', 'U-571', 'The American President', 'The Love Guru', '3000 Miles to Graceland', 'The Hateful Eight', 'Blades of Glory', 'Hop', '300', 'Meet the Fockers', 'Marley & Me', 'The Green Mile', 'Wild Hogs', 'Chicken Little', 'Gone Girl', 'The Bourne Identity', 'GoldenEye', "The General's Daughter", 'The Truman Show', 'The Prince of Egypt', 'Daddy Day Care', '2 Guns', 'Cats & Dogs', 'The Italian Job', 'Two Weeks Notice', 'Antz', 'Couples Retreat', 'Days of Thunder', 'Cheaper by the Dozen 2', 'Maze Runner: The Scorch Trials', 'Eat Pray Love', 'The Family Man', 'RED', 'Any Given Sunday', 'The Horse Whisperer', 'Collateral', 'The Scorpion King', 'Ladder 49', 'Jack Reacher', 'Deep Blue Sea', 'This Is It', 'Contagion', 'Kangaroo Jack', 'Coraline', 'The Happening', 'Man on Fire', 'The Shaggy Dog', 'Starsky & Hutch', 'Jingle All the Way', 'Hellboy', 'A Civil Action', 'ParaNorman', 'The Jackal', 'Paycheck', 'Up Close & Personal', 'The Tale of Despereaux', 'The Tuxedo', 'Under Siege 2: Dark Territory', 'Jack Ryan: Shadow Recruit', 'Joy', 'London Has Fallen', 'Alien: Resurrection', 'Shooter', 'The Boxtrolls', 'Practical Magic', 'The Lego Movie', 'Miss Congeniality 2: Armed and Fabulous', 'Reign of Fire', 'Gangster Squad', 'Year One', 'Invictus', 'State of Play', 'Duplicity', 'My Favorite Martian', 'The Sentinel', 'Planet 51', 'Star Trek: Nemesis', 'Intolerable Cruelty', 'Trouble with the Curve', 'Edge of Darkness', 'The Relic', 'Analyze That', 'Righteous Kill', 'Mercury Rising', 'The Soloist', 'The Legend of Bagger Vance', 'Almost Famous', 'Garfield: A Tail of Two Kitties', 'xXx: State of the Union', 'Priest', 'Sinbad: Legend of the Seven Seas', 'Event Horizon', 'Dragonfly', 'The Black Dahlia', 'Flyboys', 'The Last Castle', 'Supernova', "Winter's Tale", 'The Mortal Instruments: City of Bones', 'Meet Dave', 'Dark Water', 'Edtv', 'Inkheart', 'The Spirit', 'Mortdecai', 'In the Name of the King: A Dungeon Siege Tale', 'Beyond Borders', 'The Monkey King 2', 'The Great Raid', 'Deadpool', 'Holy Man', 'American Sniper', 'Goosebumps', 'Just Like Heaven', 'The Flintstones in Viva Rock Vegas', 'Rambo III', 'Leatherheads', 'The Ridiculous 6', 'Did You Hear About the Morgans?', 'The Internship', 'Resident Evil: Afterlife', 'Red Tails', "The Devil's Advocate", "That's My Boy", 'DragonHeart', 'After the Sunset', 'Ghost Rider: Spirit of Vengeance', "Captain Corelli's Mandolin", 'The Pacifier', 'Walking Tall', 'Forrest Gump', 'Alvin and the Chipmunks', 'Meet the Parents', 'Pocahontas', 'Superman', 'The Nutty Professor', 'Hitch', 'George of the Jungle', 'American Wedding', 'Captain Phillips', 'Date Night', 'Casper', 'The Equalizer', 'Maid in Manhattan', 'Crimson Tide', 'The Pursuit of Happyness', 'Flightplan', 'Disclosure', 'City of Angels', 'Kill Bill: Vol. 1', 'Bowfinger', 'Kill Bill: Vol. 2', 'Tango & Cash', 'Death Becomes Her', 'Shanghai Noon', 'Executive Decision', "Mr. Popper's Penguins", 'The Forbidden Kingdom', 'Free Birds', 'Alien³', 'Evita', 'Ronin', 'The Ghost and the Darkness', 'Paddington', 'The Watch', 'The Hunted', 'Instinct', 'Stuck on You', 'Semi-Pro', 'The Pirates! In an Adventure with Scientists!', 'Changeling', 'Chain Reaction', 'The Fan', 'The Phantom of the Opera', 'Elizabeth: The Golden Age', 'Æon Flux', 'Gods and Generals', 'Turbulence', 'Imagine That', 'Muppets Most Wanted', 'Thunderbirds', 'Burlesque', 'A Very Long Engagement', 'Lolita', 'D-Tox', 'Blade II', 'Seven Pounds', 'Bullet to the Head', 'The Godfather: Part III', 'Elizabethtown', 'You, Me and Dupree', 'Superman II', 'Gigli', "All the King's Men", 'Shaft', 'Anastasia', 'Moulin Rouge!', 'Domestic Disturbance', 'Black Mass', 'Flags of Our Fathers', 'Law Abiding Citizen', 'Grindhouse', 'Beloved', 'Lucky You', 'Catch Me If You Can', 'Zero Dark Thirty', 'The Break-Up', 'Mamma Mia!', "Valentine's Day", 'The Dukes of Hazzard', 'The Thin Red Line', 'The Change-Up', 'Man on the Moon', 'Casino', 'From Paris with Love', 'Bulletproof Monk', 'Me, Myself & Irene', 'Barnyard', 'Deck the Halls', 'The Twilight Saga: New Moon', 'Shrek', 'The Adjustment Bureau', 'Robin Hood: Prince of Thieves', 'Jerry Maguire', 'Ted', 'As Good as It Gets', 'Patch Adams', 'Anchorman 2: The Legend Continues', 'Mr. Deeds', 'Super 8', 'Erin Brockovich', 'How to Lose a Guy in 10 Days', '22 Jump Street', 'Interview with the Vampire', 'Yes Man', 'Central Intelligence', 'Stepmom', "Daddy's Home", 'Into the Woods', 'Inside Man', 'Payback', 'Congo', 'We Bought a Zoo', 'Knowing', 'Failure to Launch', 'The Ring Two', 'Crazy, Stupid, Love.', 'Garfield', 'Christmas with the Kranks', 'Moneyball', 'Outbreak', 'Non-Stop', 'Race to Witch Mountain', 'V for Vendetta', 'Shanghai Knights', 'Curious George', 'Herbie Fully Loaded', "Don't Say a Word", 'Hansel & Gretel: Witch Hunters', 'Unfaithful', 'I Am Number Four', 'Syriana', '13 Hours: The Secret Soldiers of Benghazi', 'The Book of Life', 'Firewall', 'Absolute Power', 'G.I. Jane', 'The Game', 'Silent Hill', 'The Replacements', 'American Reunion', 'The Negotiator', 'Into the Storm', 'Beverly Hills Cop III', 'Gremlins 2: The New Batch', 'The Judge', 'The Peacemaker', 'Resident Evil: Apocalypse', 'Bridget Jones: The Edge of Reason', 'Out of Time', 'On Deadly Ground', 'The Adventures of Sharkboy and Lavagirl', 'The Beach', 'Raising Helen', 'Ninja Assassin', 'For Love of the Game', 'Striptease', 'Marmaduke', 'Hereafter', 'Murder by Numbers', 'Assassins', 'Hannibal Rising', 'The Story of Us', 'The Host', 'Basic', 'Blood Work', 'The International', 'Escape from L.A.', 'The Iron Giant', 'The Life Aquatic with Steve Zissou', 'Free State of Jones', 'The Life of David Gale', 'Man of the House', 'Run All Night', 'Eastern Promises', 'Into the Blue', 'The Messenger: The Story of Joan of Arc', 'Your Highness', 'Dream House', 'Mad City', "Baby's Day Out", 'The Scarlet Letter', 'Fair Game', 'Domino', 'Jade', 'Gamer', 'Beautiful Creatures', 'Death to Smoochy', 'Zoolander 2', 'The Big Bounce', 'What Planet Are You From?', 'Drive Angry', 'Street Fighter: The Legend of Chun-Li', 'The One', 'Th

In [18]:
#recommending the right movie
find_close_match = difflib.get_close_matches(movie_name, title)
print(find_close_match)

['Legends of the Fall', 'End of the Spear', 'The Legend of the Lone Ranger']

In [19]:
first_movie = find_close_match[0]
print(first_movie)

Legends of the Fall

In [20]:
#find the similarity score
index_of_movie = movies_data[movies_data.title == first_movie]['index'].values[0]
print(index_of_movie)

1564

In [21]:
#getting similar movies
similarity_score = list(enumerate(cosine_similarity[index_of_movie]))
print(similarity_score)

[(0, np.float64(0.08062721949560303)), (1, np.float64(0.10378117928435038)), (2, np.float64(0.04873576158497956)), (3, np.float64(0.05448171151921527)), (4, np.float64(0.09566301628057698)), (5, np.float64(0.04324266008128484)), (6, np.float64(0.0075799196172201865)), (7, np.float64(0.03133026417168935)), (8, np.float64(0.007734977741039783)), (9, np.float64(0.05869435821732295)), (10, np.float64(0.05808614475199281)), (11, np.float64(0.006652723741978349)), (12, np.float64(0.00764652586082602)), (13, np.float64(0.019717743605306988)), (14, np.float64(0.10299665749183531)), (15, np.float64(0.10008160169690698)), (16, np.float64(0.029707750307328265)), (17, np.float64(0.007314789679910466)), (18, np.float64(0.013280390819523594)), (19, np.float64(0.03060254913537262)), (20, np.float64(0.05314152725463352)), (21, np.float64(0.006285004218695615)), (22, np.float64(0.019317679026497243)), (23, np.float64(0.030514621820300118)), (24, np.float64(0.08378997130541452)), (25, np.float64(0.020239471139689758)), (26, np.float64(0.14843603379806108)), (27, np.float64(0.04861104451450553)), (28, np.float64(0.02139139677204978)), (29, np.float64(0.018553197970021456)), (30, np.float64(0.007547661205800607)), (31, np.float64(0.07323171564324552)), (32, np.float64(0.04407005156802264)), (33, np.float64(0.03113559984787408)), (34, np.float64(0.0)), (35, np.float64(0.007885808100879535)), (36, np.float64(0.03460740262772435)), (37, np.float64(0.007874262341536431)), (38, np.float64(0.03167801273247267)), (39, np.float64(0.020143293771803367)), (40, np.float64(0.022662483601305985)), (41, np.float64(0.007214123797065081)), (42, np.float64(0.0)), (43, np.float64(0.09151218767495384)), (44, np.float64(0.0)), (45, np.float64(0.05546989087771347)), (46, np.float64(0.0565601478096944)), (47, np.float64(0.04561930235935089)), (48, np.float64(0.031804055790761114)), (49, np.float64(0.053475250816594905)), (50, np.float64(0.1117512931583288)), (51, np.float64(0.006147358401282373)), (52, np.float64(0.019321852113802208)), (53, np.float64(0.07788137493441474)), (54, np.float64(0.006789952390486451)), (55, np.float64(0.007878466454727333)), (56, np.float64(0.008399776114389182)), (57, np.float64(0.023787099450678396)), (58, np.float64(0.027336617261936966)), (59, np.float64(0.04877376847876121)), (60, np.float64(0.044909207162261926)), (61, np.float64(0.014385445380813235)), (62, np.float64(0.0074148979265312685)), (63, np.float64(0.1376759966524044)), (64, np.float64(0.038072740228461965)), (65, np.float64(0.0029770697608971657)), (66, np.float64(0.020223770911369388)), (67, np.float64(0.007730811300445933)), (68, np.float64(0.007022688843134072)), (69, np.float64(0.035911886467300425)), (70, np.float64(0.030475754202523447)), (71, np.float64(0.009844522462196569)), (72, np.float64(0.007266218100283953)), (73, np.float64(0.013638939432251241)), (74, np.float64(0.02911414310309226)), (75, np.float64(0.03339917386454476)), (76, np.float64(0.007551179638388787)), (77, np.float64(0.016441648813053423)), (78, np.float64(0.0557334439285894)), (79, np.float64(0.0657224322263916)), (80, np.float64(0.02631774736103683)), (81, np.float64(0.04000145525637415)), (82, np.float64(0.0030784506186874736)), (83, np.float64(0.014856778595509648)), (84, np.float64(0.027561911039697885)), (85, np.float64(0.03217098608184964)), (86, np.float64(0.006392447747401272)), (87, np.float64(0.08243561255087746)), (88, np.float64(0.14134977830920858)), (89, np.float64(0.018340793598261042)), (90, np.float64(0.0072782225913179295)), (91, np.float64(0.007243107770934423)), (92, np.float64(0.01554527562378122)), (93, np.float64(0.0558293830804045)), (94, np.float64(0.007280300660100997)), (95, np.float64(0.0719361069959826)), (96, np.float64(0.03511474973038585)), (97, np.float64(0.008090535273637425)), (98, np.float64(0.05409473127966331)), (99, np.float64(0.0)), (100, np.float64(0.14347849080423444)), (101, np.float64(0.055619145161064816)), (102, np.float64(0.02267206147068336)), (103, np.float64(0.024978702498996103)), (104, np.float64(0.0106339510688129)), (105, np.float64(0.04054135393980429)), (106, np.float64(0.007869067822975173)), (107, np.float64(0.007932940038912453)), (108, np.float64(0.06536508096603863)), (109, np.float64(0.034633149197746224)), (110, np.float64(0.08321815319413885)), (111, np.float64(0.09534295847553284)), (112, np.float64(0.08430877685427468)), (113, np.float64(0.021748489521601556)), (114, np.float64(0.006858543358710343)), (115, np.float64(0.0)), (116, np.float64(0.06402127829460212)), (117, np.float64(0.08178559508118984)), (118, np.float64(0.09397607874639537)), (119, np.float64(0.017699556453000885)), (120, np.float64(0.01364753015515907)), (121, np.float64(0.04280172370496568)), (122, np.float64(0.023140476306348967)), (123, np.float64(0.04792568394171323)), (124, np.float64(0.019000902238956327)), (125, np.float64(0.0471814840383101)), (126, np.float64(0.09225130800155856)), (127, np.float64(0.007885059233896421)), (128, np.float64(0.04264519539752305)), (129, np.float64(0.06322445802676153)), (130, np.float64(0.006677748111767996)), (131, np.float64(0.05564013176954223)), (132, np.float64(0.01969877910661959)), (133, np.float64(0.0)), (134, np.float64(0.007067053338615174)), (135, np.float64(0.11851147122766442)), (136, np.float64(0.006613033149224708)), (137, np.float64(0.014265385221032162)), (138, np.float64(0.03478259462742623)), (139, np.float64(0.047982149009894545)), (140, np.float64(0.01732153571283927)), (141, np.float64(0.007252415243397921)), (142, np.float64(0.008135536833817233)), (143, np.float64(0.04062901305158128)), (144, np.float64(0.031404773072134164)), (145, np.float64(0.18769047952860335)), (146, np.float64(0.0)), (147, np.float64(0.01872566231180218)), (148, np.float64(0.0)), (149, np.float64(0.06326771492946018)), (150, np.float64(0.04977269637051518)), (151, np.float64(0.060836450496477124)), (152, np.float64(0.020094861946408683)), (153, np.float64(0.030976194245400684)), (154, np.float64(0.0)), (155, np.float64(0.038101347220771686)), (156, np.float64(0.14811747285529345)), (157, np.float64(0.010937770420648345)), (158, np.float64(0.05629535147953248)), (159, np.float64(0.0)), (160, np.float64(0.048774488329088)), (161, np.float64(0.04218503179398309)), (162, np.float64(0.01691487487737021)), (163, np.float64(0.021215209627154175)), (164, np.float64(0.046344451594483534)), (165, np.float64(0.01858601284599665)), (166, np.float64(0.00876567213891022)), (167, np.float64(0.051021166200713314)), (168, np.float64(0.007138471730269827)), (169, np.float64(0.06578648862937617)), (170, np.float64(0.06404394991875019)), (171, np.float64(0.04542959953652059)), (172, np.float64(0.036670613509275904)), (173, np.float64(0.0)), (174, np.float64(0.05210197082060677)), (175, np.float64(0.08753636595817724)), (176, np.float64(0.09217685779220386)), (177, np.float64(0.0)), (178, np.float64(0.006962015653117718)), (179, np.float64(0.022089124305755905)), (180, np.float64(0.0764947224748182)), (181, np.float64(0.007695355595784412)), (182, np.float64(0.02982594240850306)), (183, np.float64(0.08266804351596893)), (184, np.float64(0.0)), (185, np.float64(0.007483586620142541)), (186, np.float64(0.018607978531536732)), (187, np.float64(0.014188807988470255)), (188, np.float64(0.029376561596430525)), (189, np.float64(0.15145533837086778)), (190, np.float64(0.014040427032493277)), (191, np.float64(0.020560450837996572)), (192, np.float64(0.062064904441305954)), (193, np.float64(0.007890620046665209)), (194, np.float64(0.0)), (195, np.float64(0.020131333616951387)), (196, np.float64(0.1218038531200957)), (197, np.float64(0.03588501790443603)), (198, np.float64(0.01416114797499997)), (199, np.float64(0.019031238819431577)), (200, np.float64(0.05220305128379377)), (201, np.float64(0.05826131839927928)), (202, np.float64(0.0071944692459100165)), (203, np.float64(0.04062509181253785)), (204, np.float64(0.03600306141760333)), (205, np.float64(0.02213318889947895)), (206, np.float64(0.006898245521758133)), (207, np.float64(0.006930221684760927)), (208, np.float64(0.020445875995066233)), (209, np.float64(0.027807948526146493)), (210, np.float64(0.0)), (211, np.float64(0.013860019488171178)), (212, np.float64(0.049157730075509845)), (213, np.float64(0.023351356380984283)), (214, np.float64(0.017201485751867352)), (215, np.float64(0.037044713750381604)), (216, np.float64(0.022485546133855734)), (217, np.float64(0.029225228040661567)), (218, np.float64(0.033245680673999585)), (219, np.float64(0.02366753429868554)), (220, np.float64(0.019080543437578833)), (221, np.float64(0.007902802169612914)), (222, np.float64(0.0030217166833737454)), (223, np.float64(0.025254190750219)), (224, np.float64(0.01334057841073726)), (225, np.float64(0.04860129212432755)), (226, np.float64(0.011226238214688664)), (227, np.float64(0.0)), (228, np.float64(0.007041024833178045)), (229, np.float64(0.021874554642187256)), (230, np.float64(0.005880183580937662)), (231, np.float64(0.0)), (232, np.float64(0.0604939349885033)), (233, np.float64(0.05975559981168893)), (234, np.float64(0.0529139104862269)), (235, np.float64(0.02574352145933725)), (236, np.float64(0.09183511358036671)), (237, np.float64(0.022651445223216268)), (238, np.float64(0.006877594151465238)), (239, np.float64(0.0026181248693704323)), (240, np.float64(0.021690627972986973)), (241, np.float64(0.12766903593829013)), (242, np.float64(0.007937901411837176)), (243, np.float64(0.007330462324881632)), (244, np.float64(0.024104157725697885)), (245, np.float64(0.01844817983763742)), (246, np.float64(0.029665886076331048)), (247, np.float64(0.09362324134770107)), (248, np.float64(0.06398887812277385)), (249, np.float64(0.0476960613802794)), (250, np.float64(0.04105490135728714)), (251, np.float64(0.0)), (252, np.float64(0.04146887928208596)), (253, np.float64(0.057899499851212)), (254, np.float64(0.02897312060229233)), (255, np.float64(0.0)), (256, np.float64(0.09118998650802289)), (257, np.float64(0.037569293763694875)), (258, np.float64(0.023038630452626087)), (259, np.float64(0.03133524605591276)), (260, np.float64(0.04695602571622989)), (261, np.float64(0.015878721803634182)), (262, np.float64(0.007311060466094126)), (263, np.float64(0.0072804461013524)), (264, np.float64(0.0027590685603082125)), (265, np.float64(0.07015323892292966)), (266, np.float64(0.04057687066228903)), (267, np.float64(0.06656643885455205)), (268, np.float64(0.1567517391182484)), (269, np.float64(0.07069761595876792)), (270, np.float64(0.05439966946997945)), (271, np.float64(0.008193813603384809)), (272, np.float64(0.006621809051545877)), (273, np.float64(0.09476802292453333)), (274, np.float64(0.011142299705390489)), (275, np.float64(0.050413243077990215)), (276, np.float64(0.02147867015893819)), (277, np.float64(0.039392909562628586)), (278, np.float64(0.0065853371942470335)), (279, np.float64(0.028795114706138443)), (280, np.float64(0.024415190408028822)), (281, np.float64(0.016043895805076574)), (282, np.float64(0.0)), (283, np.float64(0.0024432080319021134)), (284, np.float64(0.006926063597263776)), (285, np.float64(0.025451620156768863)), (286, np.float64(0.0029298768951734238)), (287, np.float64(0.016727763915261776)), (288, np.float64(0.05192783553230776)), (289, np.float64(0.00714976952135412)), (290, np.float64(0.03755734291296491)), (291, np.float64(0.026047138231783513)), (292, np.float64(0.0750592249684019)), (293, np.float64(0.0)), (294, np.float64(0.04025954656659408)), (295, np.float64(0.013163145024588303)), (296, np.float64(0.01452843384260858)), (297, np.float64(0.08099790861629497)), (298, np.float64(0.003060000896181499)), (299, np.float64(0.0)), (300, np.float64(0.017700447093741467)), (301, np.float64(0.0030045209664751357)), (302, np.float64(0.048709838226411006)), (303, np.float64(0.0)), (304, np.float64(0.03713076645645738)), (305, np.float64(0.061324056668496364)), (306, np.float64(0.03330941209171637)), (307, np.float64(0.007243694029516591)), (308, np.float64(0.011843788386836725)), (309, np.float64(0.008530820680780043)), (310, np.float64(0.04690079707441839)), (311, np.float64(0.0)), (312, np.float64(0.0344665638763734)), (313, np.float64(0.033179409348607955)), (314, np.float64(0.0325019303089911)), (315, np.float64(0.04010136472648221)), (316, np.float64(0.04688911196047918)), (317, np.float64(0.029119187018086773)), (318, np.float64(0.06081591131462292)), (319, np.float64(0.014718590064832183)), (320, np.float64(0.058036244512935195)), (321, np.float64(0.013250147618149832)), (322, np.float64(0.007744100066320068)), (323, np.float64(0.026799837223003484)), (324, np.float64(0.0639395357958373)), (325, np.float64(0.0402979950672233)), (326, np.float64(0.02381268957643377)), (327, np.float64(0.05925750095659621)), (328, np.float64(0.043911140021466274)), (329, np.float64(0.07382773291616543)), (330, np.float64(0.04784706223246028)), (331, np.float64(0.03562022291627368)), (332, np.float64(0.017370834153882943)), (333, np.float64(0.002536073405671372)), (334, np.float64(0.019972361945721405)), (335, np.float64(0.00289615773281218)), (336, np.float64(0.09951441736534446)), (337, np.float64(0.0)), (338, np.float64(0.02910838916983201)), (339, np.float64(0.03536689913979447)), (340, np.float64(0.03286374473386055)), (341, np.float64(0.007134818094673798)), (342, np.float64(0.06500662371252965)), (343, np.float64(0.014200243172322564)), (344, np.float64(0.0)), (345, np.float64(0.0)), (346, np.float64(0.014958736030120047)), (347, np.float64(0.0)), (348, np.float64(0.007338217789781213)), (349, np.float64(0.009776828222672307)), (350, np.float64(0.008805565413741173)), (351, np.float64(0.003053550227959735)), (352, np.float64(0.032302802710403214)), (353, np.float64(0.011301428878440656)), (354, np.float64(0.04175719829997571)), (355, np.float64(0.0)), (356, np.float64(0.007708842918060595)), (357, np.float64(0.002938699265584243)), (358, np.float64(0.006882895055455514)), (359, np.float64(0.007172301002792005)), (360, np.float64(0.03087072469595822)), (361, np.float64(0.04295023624032966)), (362, np.float64(0.0109993024912641)), (363, np.float64(0.021639920744026805)), (364, np.float64(0.012132968407784548)), (365, np.float64(0.03882965119568784)), (366, np.float64(0.0)), (367, np.float64(0.013555693970019883)), (368, np.float64(0.0063644578993027855)), (369, np.float64(0.03665115547684915)), (370, np.float64(0.00763655791051683)), (371, np.float64(0.044715140295283395)), (372, np.float64(0.10788156459956871)), (373, np.float64(0.0)), (374, np.float64(0.006613057314530408)), (375, np.float64(0.030059806054652805)), (376, np.float64(0.015771157470858117)), (377, np.float64(0.11041678235981962)), (378, np.float64(0.00266991375653384)), (379, np.float64(0.006332655078108436)), (380, np.float64(0.04830069999570463)), (381, np.float64(0.0)), (382, np.float64(0.026486793023110636)), (383, np.float64(0.03533406212512529)), (384, np.float64(0.13082898564589102)), (385, np.float64(0.0)), (386, np.float64(0.07398062137402382)), (387, np.float64(0.03775415624957787)), (388, np.float64(0.09097221700310097)), (389, np.float64(0.038409039753995)), (390, np.float64(0.022213028125171678)), (391, np.float64(0.006305127250163431)), (392, np.float64(0.0)), (393, np.float64(0.02811143912665999)), (394, np.float64(0.0)), (395, np.float64(0.00582791653645623)), (396, np.float64(0.04490608893371805)), (397, np.float64(0.006907905611234013)), (398, np.float64(0.07143157961102765)), (399, np.float64(0.0064668279018710185)), (400, np.float64(0.04176141375592052)), (401, np.float64(0.09004369790296415)), (402, np.float64(0.020933096575091074)), (403, np.float64(0.01984514420295947)), (404, np.float64(0.08378438830165903)), (405, np.float64(0.04690362968340338)), (406, np.float64(0.002691136665633027)), (407, np.float64(0.1031679480673431)), (408, np.float64(0.0029686127225265297)), (409, np.float64(0.0016786900990481753)), (410, np.float64(0.07853747202108838)), (411, np.float64(0.016430368602473273)), (412, np.float64(0.01974549944269255)), (413, np.float64(0.021338908919631666)), (414, np.float64(0.007236935131548016)), (415, np.float64(0.0)), (416, np.float64(0.035686401830267896)), (417, np.float64(0.012340092192644307)), (418, np.float64(0.026286022834953467)), (419, np.float64(0.05132864185687726)), (420, np.float64(0.049912668955006026)), (421, np.float64(0.02510782875670137)), (422, np.float64(0.0)), (423, np.float64(0.0)), (424, np.float64(0.00734284476440031)), (425, np.float64(0.0544473114844191)), (426, np.float64(0.02004211602340542)), (427, np.float64(0.013951542667247739)), (428, np.float64(0.04402405389493555)), (429, np.float64(0.011907693378183043)), (430, np.float64(0.011992809657425893)), (431, np.float64(0.0415926683318553)), (432, np.float64(0.009649116315740365)), (433, np.float64(0.07540227109985234)), (434, np.float64(0.0030615604991250747)), (435, np.float64(0.0)), (436, np.float64(0.0)), (437, np.float64(0.048818003856412426)), (438, np.float64(0.010849378367484145)), (439, np.float64(0.04731333650758577)), (440, np.float64(0.009281409544781724)), (441, np.float64(0.0)), (442, np.float64(0.0)), (443, np.float64(0.006175788290220947)), (444, np.float64(0.050302012897907124)), (445, np.float64(0.0064122417568769135)), (446, np.float64(0.023293185026523153)), (447, np.float64(0.023629317650944174)), (448, np.float64(0.05059569262367904)), (449, np.float64(0.0)), (450, np.float64(0.0)), (451, np.float64(0.039065075470548244)), (452, np.float64(0.0024809098001102726)), (453, np.float64(0.0)), (454, np.float64(0.02608574156544528)), (455, np.float64(0.030359810281482744)), (456, np.float64(0.18915237235350937)), (457, np.float64(0.05167943148693131)), (458, np.float64(0.007445424238118183)), (459, np.float64(0.03755789086978987)), (460, np.float64(0.007007443524584155)), (461, np.float64(0.04344214186469986)), (462, np.float64(0.031081776569744434)), (463, np.float64(0.039268807202862556)), (464, np.float64(0.0)), (465, np.float64(0.0)), (466, np.float64(0.031455686272611506)), (467, np.float64(0.008394630823074432)), (468, np.float64(0.009874808841103965)), (469, np.float64(0.031510465524150474)), (470, np.float64(0.07260392820310935)), (471, np.float64(0.06567807553953844)), (472, np.float64(0.10404437566435219)), (473, np.float64(0.043094914895636716)), (474, np.float64(0.0027668834355299584)), (475, np.float64(0.06666903749014595)), (476, np.float64(0.014163950219030767)), (477, np.float64(0.0027587501513554875)), (478, np.float64(0.007376637144996745)), (479, np.float64(0.030890508799563683)), (480, np.float64(0.08469263572579847)), (481, np.float64(0.0)), (482, np.float64(0.008564797643341539)), (483, np.float64(0.05703074572037867)), (484, np.float64(0.03333373582805188)), (485, np.float64(0.021473284367636326)), (486, np.float64(0.0071283118119660465)), (487, np.float64(0.0)), (488, np.float64(0.02505292535939529)), (489, np.float64(0.041561558409462546)), (490, np.float64(0.03983792184577784)), (491, np.float64(0.014917317860056133)), (492, np.float64(0.0)), (493, np.float64(0.010025478280281774)), (494, np.float64(0.03954534912813802)), (495, np.float64(0.06068749656060267)), (496, np.float64(0.0)), (497, np.float64(0.10965595204424214)), (498, np.float64(0.006740910306388061)), (499, np.float64(0.014605378195985029)), (500, np.float64(0.0)), (501, np.float64(0.029387099671244404)), (502, np.float64(0.025942007390311935)), (503, np.float64(0.050232955958085225)), (504, np.float64(0.0)), (505, np.float64(0.0558503733862559)), (506, np.float64(0.014015524596815307)), (507, np.float64(0.007261568674090176)), (508, np.float64(0.007440992637762889)), (509, np.float64(0.0)), (510, np.float64(0.030010256691855763)), (511, np.float64(0.06420735857882322)), (512, np.float64(0.021347913535917355)), (513, np.float64(0.014426733048511192)), (514, np.float64(0.015900399385638628)), (515, np.float64(0.01816039301699561)), (516, np.float64(0.04752058208306757)), (517, np.float64(0.013170634883470495)), (518, np.float64

In [22]:
len(similarity_score)

4803

In [23]:
# sorting the similarity in reverse order
sorted_similar_movies = sorted(similarity_score, key = lambda x:x[1], reverse = True)
print(sorted_similar_movies)

[(1564, np.float64(1.0000000000000002)), (456, np.float64(0.18915237235350937)), (145, np.float64(0.18769047952860335)), (2296, np.float64(0.17734598431436926)), (1796, np.float64(0.17514650559563022)), (2550, np.float64(0.17443057045642316)), (628, np.float64(0.17426808929964138)), (535, np.float64(0.1659102619950851)), (1134, np.float64(0.16395191698605546)), (268, np.float64(0.1567517391182484)), (1662, np.float64(0.15482187600251024)), (889, np.float64(0.15462416696417725)), (1459, np.float64(0.15344599541052978)), (1787, np.float64(0.15337601737362136)), (3837, np.float64(0.15321675987186636)), (189, np.float64(0.15145533837086778)), (1120, np.float64(0.1511481259839711)), (3227, np.float64(0.15076721888223102)), (2635, np.float64(0.14908191718796007)), (2060, np.float64(0.14873175087131704)), (3957, np.float64(0.14853028397740772)), (26, np.float64(0.14843603379806108)), (3057, np.float64(0.1483713106267287)), (156, np.float64(0.14811747285529345)), (3039, np.float64(0.1467312714278887)), (3495, np.float64(0.14656149625129203)), (4152, np.float64(0.14543817947565926)), (3445, np.float64(0.14480419438623138)), (100, np.float64(0.14347849080423444)), (4239, np.float64(0.1434038633188507)), (2196, np.float64(0.1431874611009485)), (787, np.float64(0.14229809594623372)), (586, np.float64(0.14205779457695333)), (1373, np.float64(0.1417070340294725)), (88, np.float64(0.14134977830920858)), (2068, np.float64(0.14055217303016815)), (1112, np.float64(0.13980753929381495)), (592, np.float64(0.1391689730768539)), (642, np.float64(0.1385376579603036)), (63, np.float64(0.1376759966524044)), (1117, np.float64(0.13629498422862152)), (2081, np.float64(0.13192055297512204)), (384, np.float64(0.13082898564589102)), (599, np.float64(0.1307946665760495)), (3270, np.float64(0.13013467457945607)), (1183, np.float64(0.12992794998476964)), (1446, np.float64(0.12956076129863742)), (2091, np.float64(0.12952739515475284)), (1921, np.float64(0.1292892221985002)), (2578, np.float64(0.1278229563835323)), (241, np.float64(0.12766903593829013)), (1651, np.float64(0.12720459163945577)), (2024, np.float64(0.12712201819619764)), (3236, np.float64(0.12408069357779918)), (1047, np.float64(0.1240804020790016)), (1382, np.float64(0.1233459801378759)), (1036, np.float64(0.12256227902498185)), (2946, np.float64(0.12217405676887129)), (561, np.float64(0.12191619554469758)), (196, np.float64(0.1218038531200957)), (531, np.float64(0.12100559978038238)), (1891, np.float64(0.12028357151562726)), (2678, np.float64(0.1195175628840021)), (708, np.float64(0.11933892486527198)), (2555, np.float64(0.11901193076952826)), (135, np.float64(0.11851147122766442)), (2986, np.float64(0.11795411702649515)), (2522, np.float64(0.11758746091504017)), (1977, np.float64(0.11594826744058287)), (2708, np.float64(0.11578878445338174)), (1282, np.float64(0.11520682684041768)), (1818, np.float64(0.11458326003057115)), (2442, np.float64(0.11454641905505981)), (2587, np.float64(0.1138360369368774)), (2888, np.float64(0.11350617183048606)), (615, np.float64(0.11308500602437643)), (1696, np.float64(0.11252560103396636)), (2436, np.float64(0.11239205625906884)), (830, np.float64(0.11205081302731545)), (50, np.float64(0.1117512931583288)), (3826, np.float64(0.1116191345380866)), (1187, np.float64(0.11111413503811368)), (677, np.float64(0.11101824104432917)), (928, np.float64(0.1106691102726844)), (2032, np.float64(0.11045523863064816)), (377, np.float64(0.11041678235981962)), (855, np.float64(0.11004269868992217)), (497, np.float64(0.10965595204424214)), (2025, np.float64(0.10820317645279622)), (3723, np.float64(0.10806170478632036)), (372, np.float64(0.10788156459956871)), (2914, np.float64(0.10787052532572938)), (1698, np.float64(0.10781939079925128)), (3914, np.float64(0.10769535928901672)), (3644, np.float64(0.10762252961583801)), (2829, np.float64(0.10715130303502324)), (673, np.float64(0.106988557908688)), (1855, np.float64(0.10692712910569448)), (946, np.float64(0.10628935584892461)), (4076, np.float64(0.10622594071771353)), (591, np.float64(0.10596132639904282)), (800, np.float64(0.10565533407766362)), (3813, np.float64(0.10561726119879607)), (3177, np.float64(0.10554859311127539)), (2233, np.float64(0.1054813199658564)), (3032, np.float64(0.10523786305414531)), (842, np.float64(0.10512297111585925)), (472, np.float64(0.10404437566435219)), (1, np.float64(0.10378117928435038)), (2153, np.float64(0.10345484653357793)), (3026, np.float64(0.10344711344115762)), (407, np.float64(0.1031679480673431)), (809, np.float64(0.10306545726385284)), (14, np.float64(0.10299665749183531)), (3373, np.float64(0.10261751404844127)), (4062, np.float64(0.10260315966457886)), (3061, np.float64(0.10248512402533917)), (3142, np.float64(0.10202124164852362)), (2757, np.float64(0.10163979226788336)), (2904, np.float64(0.10161604723539451)), (1490, np.float64(0.10150025291628902)), (2642, np.float64(0.10140471847344855)), (2341, np.float64(0.10050849113277048)), (4231, np.float64(0.10045702573760551)), (15, np.float64(0.10008160169690698)), (4465, np.float64(0.10000495155868461)), (1895, np.float64(0.09974834876904537)), (1174, np.float64(0.099729439194737)), (3171, np.float64(0.09967315098210432)), (336, np.float64(0.09951441736534446)), (4661, np.float64(0.09947010995884815)), (1523, np.float64(0.0993714928819455)), (585, np.float64(0.09909734211198225)), (2629, np.float64(0.09871587393964976)), (979, np.float64(0.09864441963030456)), (2424, np.float64(0.09833974416539656)), (1094, np.float64(0.09802616530541639)), (2898, np.float64(0.09800245160750293)), (3239, np.float64(0.09795464046061082)), (2993, np.float64(0.09748063898317118)), (2691, np.float64(0.0970610331056607)), (2590, np.float64(0.09681476472997846)), (1688, np.float64(0.09666616360223793)), (2169, np.float64(0.0966251408161422)), (3698, np.float64(0.09636568794444454)), (2572, np.float64(0.0963598335031049)), (4, np.float64(0.09566301628057698)), (111, np.float64(0.09534295847553284)), (4649, np.float64(0.09494211320563373)), (1877, np.float64(0.09480356443356729)), (273, np.float64(0.09476802292453333)), (118, np.float64(0.09397607874639537)), (627, np.float64(0.09376980894427131)), (247, np.float64(0.09362324134770107)), (3238, np.float64(0.09355799937341941)), (3508, np.float64(0.09351441434424271)), (1573, np.float64(0.09343241710513163)), (3094, np.float64(0.09314781858588428)), (2357, np.float64(0.09283813885603527)), (1775, np.float64(0.0926014289604118)), (126, np.float64(0.09225130800155856)), (176, np.float64(0.09217685779220386)), (1284, np.float64(0.09205836079335651)), (2727, np.float64(0.09205273468467323)), (236, np.float64(0.09183511358036671)), (43, np.float64(0.09151218767495384)), (2225, np.float64(0.09136713046271143)), (1231, np.float64(0.0912972766316878)), (2305, np.float64(0.09127054249542808)), (256, np.float64(0.09118998650802289)), (388, np.float64(0.09097221700310097)), (4095, np.float64(0.09024033110274925)), (2085, np.float64(0.09022637862158324)), (401, np.float64(0.09004369790296415)), (2129, np.float64(0.08962214805057073)), (4155, np.float64(0.08950174473749017)), (2860, np.float64(0.08923887117788502)), (1638, np.float64(0.08915302712441468)), (1467, np.float64(0.08889010011918591)), (912, np.float64(0.08885995457675187)), (1763, np.float64(0.08883155846411257)), (1830, np.float64(0.08875290076121663)), (3643, np.float64(0.08859437389364765)), (4276, np.float64(0.08851706145671154)), (1091, np.float64(0.08808033433259581)), (870, np.float64(0.08775404755310277)), (713, np.float64(0.08763748339375645)), (175, np.float64(0.08753636595817724)), (2571, np.float64(0.08748347418710337)), (2181, np.float64(0.08721471545314788)), (1510, np.float64(0.08708121836469054)), (1440, np.float64(0.08691768606851298)), (687, np.float64(0.08682598743447226)), (3903, np.float64(0.0864714832774109)), (2052, np.float64(0.08644599775682196)), (977, np.float64(0.08621356052333956)), (3650, np.float64(0.08620649368410677)), (4371, np.float64(0.08620341575174555)), (590, np.float64(0.08602349756291164)), (2732, np.float64(0.08599775959943476)), (769, np.float64(0.08587675923217238)), (2053, np.float64(0.08577955774701798)), (3886, np.float64(0.08575527023036707)), (773, np.float64(0.08527268364750357)), (2276, np.float64(0.08517824939760951)), (480, np.float64(0.08469263572579847)), (634, np.float64(0.0844512934684823)), (1106, np.float64(0.0843706086688157)), (112, np.float64(0.08430877685427468)), (2361, np.float64(0.08422142096624562)), (24, np.float64(0.08378997130541452)), (404, np.float64(0.08378438830165903)), (1296, np.float64(0.08368666763719004)), (1890, np.float64(0.08366344961519029)), (841, np.float64(0.08326030959880534)), (110, np.float64(0.08321815319413885)), (3197, np.float64(0.083213165461902)), (3178, np.float64(0.08307885543924565)), (1840, np.float64(0.08294107972111373)), (183, np.float64(0.08266804351596893)), (571, np.float64(0.08258444540869536)), (87, np.float64(0.08243561255087746)), (2725, np.float64(0.08237807367001262)), (1158, np.float64(0.0823132552060186)), (1457, np.float64(0.08216684096261598)), (117, np.float64(0.08178559508118984)), (1195, np.float64(0.08136678091598575)), (4575, np.float64(0.08105310035588281)), (297, np.float64(0.08099790861629497)), (2121, np.float64(0.08090525611119112)), (0, np.float64(0.08062721949560303)), (1999, np.float64(0.08038214298239381)), (2444, np.float64(0.08033660886946689)), (2876, np.float64(0.07983125887917743)), (2514, np.float64(0.07973655965441148)), (1159, np.float64(0.07963562352350363)), (1944, np.float64(0.07956097308316304)), (2254, np.float64(0.07941952446602808)), (662, np.float64(0.07898181004652263)), (2049, np.float64(0.07896749941303187)), (680, np.float64(0.07888592071575819)), (873, np.float64(0.07888029397967984)), (3516, np.float64(0.07881375930168888)), (2399, np.float64(0.07876710993245256)), (648, np.float64(0.07874994116899547)), (410, np.float64(0.07853747202108838)), (878, np.float64(0.07836248200194242)), (2538, np.float64(0.07794458809008775)), (53, np.float64(0.07788137493441474)), (3205, np.float64(0.07771741566973422)), (1655, np.float64(0.07767920783278554)), (990, np.float64(0.0770895550729205)), (1240, np.float64(0.0769528185439456)), (1057, np.float64(0.07690337779650722)), (1350, np.float64(0.0768183614768846)), (180, np.float64(0.0764947224748182)), (2096, np.float64(0.076133821180428)), (3579, np.float64(0.07600751892032395)), (3514, np.float64(0.07598205403870924)), (1889, np.float64(0.07589004374736215)), (1672, np.float64(0.07585514253552374)), (3744, np.float64(0.07542005666392414)), (433, np.float64(0.07540227109985234)), (1959, np.float64(0.07539457977727124)), (2859, np.float64(0.07519786107713843)), (2798, np.float64(0.07507379513320882)), (292, np.float64(0.0750592249684019)), (4197, np.float64(0.07501632831777577)), (2167, np.float64(0.07487380110455391)), (1644, np.float64(0.07482569775662495)), (557, np.float64(0.07445980587900188)), (3285, np.float64(0.07439811188808801)), (941, np.float64(0.07398382603426501)), (386, np.float64(0.07398062137402382)), (329, np.float64(0.07382773291616543)), (3436, np.float64(0.07363798583807403)), (617, np.float64(0.07350029930913508)), (4312, np.float64(0.07344617616503973)), (31, np.float64(0.07323171564324552)), (1590, np.float64(0.07319118544666743)), (1461, np.float64(0.07294258298249427)), (470, np.float64(0.07260392820310935)), (4024, np.float64(0.0725772099982746)), (4175, np.float64(0.07251268722098334)), (3618, np.float64(0.07250323922126477)), (4749, np.float64(0.07238528553703492)), (854, np.float64(0.07231104667715546)), (1078, np.float64(0.07221376696751505)), (3583, np.float64(0.07219740795944479)), (2901, np.float64(0.07218645876529074)), (1819, np.float64(0.07215445534796797)), (755, np.float64(0.07205981689401533)), (95, np.float64(0.0719361069959826)), (1363, np.float64(0.07190594738372316)), (1707, np.float64(0.07166087228076339)), (2072, np.float64(0.07165076548059153)), (1405, np.float64(0.07163268113528545)), (3366, np.float64(0.0715018289696353)), (779, np.float64(0.07143626394739613)), (398, np.float64(0.07143157961102765)), (681, np.float64(0.0713167540980668)), (3805, np.float64(0.07130271167390452)), (2810, np.float64(0.07122464643874962)), (2247, np.float64(0.07112895973409976)), (1513, np.float64(0.07112011897060075)), (1606, np.float64(0.07105277700435605)), (2071, np.float64(0.07079847148399003)), (2040, np.float64(0.07077086677355415)), (269, np.float64(0.07069761595876792)), (2211, np.float64(0.07025063221793275)), (2947, np.float64(0.07021876983213707)), (4352, np.float64(0.07020166606448192)), (265, np.float64(0.07015323892292966)), (1052, np.float64(0.07013660945228808)), (4049, np.float64(0.069762729364941)), (1006, np.float64(0.06974057109628348)), (2716, np.float64(0.06968168113351522)), (2104, np.float64(0.06965474943306514)), (1167, np.float64(0.06963624313086736)), (4679, np.float64(0.06931995029126847)), (3593, np.float64(0.06913117846947556)), (1704, np.float64(0.06908673721750455)), (1958, np.float64(0.06898006814781246)), (1671, np.float64(0.06886966580995446)), (3750, np.float64(0.06881812722895553)), (2671, np.float64(0.06877863000450354)), (2858, np.float64(0.06874417960163692)), (2849, np.float64(0.0687118211930499)), (3014, np.float64(0.0686843729249712)), (582, np.float64(0.06865735684529617)), (1922, np.float64(0.06857590616280516)), (2340, np.float64(0.06855995501394563)), (3571, np.float64(0.06853692187779721)), (2387, np.float64(0.06849020253814826)), (1023, np.float64(0.06839585393766844)), (2547, np.float64(0.06839011641109395)), (791, np.float64(0.06824248676462408)), (2257, np.float64(0.06796882377510455)), (858, np.float64(0.06795475832799597)), (3287, np.float64(0.06794560051024691)), (1630, np.float64(0.06780641713099785)), (3722, np.float64(0.06775747502959265)), (1670, np.float64(0.06775000855062573)), (2190, np.float64(0.06771514142186916)), (1470, np.float64(0.06769102197558577)), (3448, np.float64(0.06756734243670823)), (3821, np.float64(0.06741675573536146)), (694, np.float64(0.06693991365564497)), (4408, np.float64(0.06685473283744943)), (4608, np.float64(0.06668398286476693)), (475, np.float64(0.06666903749014595)), (267, np.float64(0.06656643885455205)), (1335, np.float64(0.0664597284496378)), (3211, np.float64(0.0663330540407391)), (1400, np.float64(0.06627614145972927)), (2172, np.float64(0.06627284208350644)), (663, np.float64(0.06615551540527059)), (539, np.float64(0.06606354249624297)), (964, np.float64(0.06603817931987731)), (2479, np.float64(0.066029240986709)), (2797, np.float64(0.06594510394917069)), (2967, np.float64(0.06594432303840644)), (4173, np.float64(0.0658902381482564)), (2894, np.float64(0.06588842601875536)), (169, np.float64(0.06578648862937617)), (2016, np.float64(0.06577960005278011)), (79, np.float64(0.0657224322263916)), (471, np.float64(0.06567807553953844)), (742, np.float64(0.06562585355952849)), (845, np.float64(0.06550310674529256)), (2650, np.float64(0.06541502112310948)), (1486, np.float64(0.06536761228921308)), (108, np.float64(0.06536508096603863)), (1214, np.float64(0.06520556410009792)), (3503, np.float64(0.06517307414330241)), (764, np.float64(0.06508437164564673)), (1761, np.float64(0.06502338621624595)), (342, np.float64(0.06500662371252965)), (898, np.float64(0.06481863265963485)), (4359, np.float64(0.06465780428691478)), (3046, np.float64(0.06462713664034517)), (1409, np.float64(0.06447715703258323)), (2594, np.float64(0.0644032238204018)), (3262, np.float64(0.06438540121763367)), (1300, np.float64(0.06428980581793875)), (511, np.float64(0.06420735857882322)), (933, np.float64(0.06418408378524487)), (2397, np.float64(0.06416695779215335)), (1069, np.float64(0.0640841830207053)), (170, np.float64(0.06404394991875019)), (116, np.float64(0.06402127829460212)), (248, np.float64(0.06398887812277385)), (324, np.float64(0.0639395357958373)), (2782, np.float64(0.0639367959037174)), (2212, np.float64(0.06391376160242716)), (1832, np.float64(0.06388211290869014)), (1577, np.float64(0.06380217694028563)), (3986, np.float64(0.0637414267263495)), (1333, np.float64(0.06368388616767906)), (1935, np.float64(0.06362322094545325)), (1279, np.float64(0.06361740697474978)), (3704, np.float64(0.06348412916012669)), (149, np.float64(0.06326771492946018)), (3994, np.float64(0.06326608088963037)), (129, np.float64(0.06322445802676153)), (1039, np.float64(0.06321837518565232)), (2207, np.float64(0.06317973349263496)), (1923, np.float64(0.06316941355329302)), (1125, np.float64(0.06305008895991589)), (3654, np.float64(0.06295224149986967)), (2193, np.float64(0.06288838390172938)), (1439, np.float64(0.06275107727914297)), (3229, np.float64(0.06270434951097482)), (2474, np.float64(0.06255752071453119)), (4063, np.float64(0.06252269904686145)), (594, np.float64(0.06246787523096901)), (1015, np.float64(0.06241680442190287)), (4799, np.float64(0.062371077437296474)), (3815, np.float64(0.062316365410977695)), (3430, np.float64(0.06211247053858648)), (192, np.float64(0.062064904441305954)), (2814, np.float64(0.06204674287266187)), (689, np.float64(0.06200715722656905)), (2290, np.float64(0.06200418086285704)), (1063, np.float64(0.06189644764487647)), (2320, np.float64(0.061763814939848616)), (1469, np.float64(0.061744055830341205)), (1244, np.float64(0.06154313813734447)), (1177, np.float64(0.06151375602153507)), (3870, np.float64(0.061491325797643825)), (2353, np.float64(0.06142920952062745)), (2326, np.float64(0.061348667856509484)), (305, np.float64(0.061324056668496364)), (1330, np.float64(0.0611825035396283)), (4097, np.float64(0.06115820009922596)), (2297, np.float64(0.061157802608097514)), (696, np.float64(0.06113697348310318)), (3068, np.float64(0.06083989468497577)), (151, np.float64(0.060836450496477124)), (318, np.float64(0.06081591131462292)), (2381, np.float64(0.0607932117062573)), (1820, np.float64(0.060766543991046515)), (4537, np.float64(0.060755901378478486)), (1560, np.float64(0.06074991933961743)), (2560, np.float64(0.060722304201088)), (495, np.float64(0.06068749656060267)), (2197, np.float64(0.060660173349876154)), (1852, np.float64(0.06064464052994495)), (1176, np.float64(0.060533326740165996)), (232, np.float64(0.0604939349885033)), (4717, np.float64(0.06025137192981797)), (1280, np.float64(0.06015768516457829)), (2035, np.float64(0.060036297807090876)), (1341, np.float64(0.05986690188269106)), (3791, np.float64(0.05984399510886879)), (2994, np.float64(0.05983856150852859)), (233, np.float64(0.05975559981168893)), (1581, np.float64(0.059713347277058)), (1847, np.float64(0.05970775398159148)), (1358, np.float64(0.05965853159280958)), (1841, np.float64(0.05964252906761823)), (1109, np.float64(0.05963866692947618)), (579, np.float64(0.05957378997302422)), (3662, np.float64(0.05948031401567658)), (4654, np.float64(0.059382660070190565)), (3203, np.float64(0.05936091738338795)), (3303, np.float64(0.05933934926773204)), (640, np.float64(0.059325396376136805)), (327, np.float64(0.05925750095659621)), (1322, np.float64(0.05919008028823859)), (670, np.float64(0.059168757267701474)), (1163, np.float64(0.0589675875257947)), (4526, np.float64(0.05894811069376155)), (3417, np.float64(0.05892409253698805)), (3864, np.float64(0.05890151536559894)), (2719, np.float64(0.058854657613436445)), (2178, np.float64(0.058710093538039)), (9, np.float64(0.05869435821732295)), (1105, np.float64(0.0586932964326614)), (1291, np.float64(0.05867551978111138)), (4597, np.float64(0.05865639359496017)), (4238, np.float64(0.058633435857266485)), (1583, np.float64(0.05862270084293829)), (2343, np.float64(0.05856154002325606)), (4695, np.float64(0.058521278033603415)), (1660, np.float64(0.0584543533172386)), (201, np.float64(0.05826131839927928)), (10, np.float64(0.05808614475199281)), (1404, np.float64(0.058052484434575995)), (2202, np.float64(0.05804683503391379)), (320, np.float64(0.058036244512935195)), (2983, np.float64(0.058002204999622206)), (253, np.float64(0.057899499851212)), (717, np.float64(0

In [30]:
# loop through and print similar movies
print('You will Also like similar movies like that of', movie_name, '\n')

i = 1

for movie in sorted_similar_movies:
  index = movie[0]
  title_index = movies_data[movies_data.index == index] ['title'].values[0]
  if(i < 21):
    print(i, '.', title_index)
    i+=1

You will Also like similar movies like that of legend of the seeker

1 . Legends of the Fall
2 . Fury
3 . Troy
4 . The Bounty
5 . Brothers
6 . Lawrence of Arabia
7 . Saving Private Ryan
8 . First Knight
9 . Super Mario Bros.
10 . Stuart Little
11 . Glory
12 . The Thin Red Line
13 . Lion of the Desert
14 . A Bridge Too Far
15 . She's the One
16 . Noah
17 . Notting Hill
18 . The Wind That Shakes the Barley
19 . Funny Games
20 . Out of the Furnace

The Recommendation System

In [39]:
# Recommendation system
movie_name = input('Enter the movie name: ')
title = movies_data['title'].tolist()
find_close_match = difflib.get_close_matches(movie_name, title)

if len(find_close_match) == 0:
    print('Sorry, no close match found for the movie name you entered.')
else:
    first_movie = find_close_match[0]
    index_of_movie = movies_data[movies_data.title == first_movie]['index'].values[0]
    similarity_score = list(enumerate(cosine_similarity[index_of_movie]))
    sorted_similar_movies = sorted(similarity_score, key = lambda x:x[1], reverse = True)

    print('This Movies are similar to', first_movie, '\n')

    i = 1

    for movie in sorted_similar_movies:
      index = movie[0]
      title_index = movies_data[movies_data.index == index] ['title'].values[0]
      if(i < 21):
        print(i, '.', title_index)
        i+=1

Enter the movie name: titanic
This Movies are similar to Titanic

1 . Titanic
2 . The Dilemma
3 . The Day the Earth Stood Still
4 . Revolutionary Road
5 . Cheri
6 . Heavenly Creatures
7 . Plush
8 . Primary Colors
9 . The Bridge of San Luis Rey
10 . Saving Silverman
11 . Gangs of New York
12 . Flushed Away
13 . Sense and Sensibility
14 . Stuck on You
15 . The Great Gatsby
16 . Almost Famous
17 . Shutter Island
18 . The Brothers Bloom
19 . Contagion
20 . The Blind Side